Feature/exercicio 01
charles-oliveira/orion-bootcamp pull request #1
Opened 2023-10-09 15:02 UTC by charles-oliveira

2023-10-09 16:10 UTC, FLindenmeyer commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Fabrício Linden.] Exercício 1](https://trello.com/c/r2U6SvFc/67-fabr%C3%ADcio-linden-exerc%C3%ADcio-1)

2023-10-09 17:27 UTC, aLiviaMs requested changes

2023-10-09 17:27 UTC, aLiviaMs commented on src/exercicio-01.ts
> +  const vogais = ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U']
Em vez de escrever as vogais em maiúscula e minúsculo, uma boa prática é transformar o valor `palavra` para lowerCase ou UpperCase, assim não há repetição no array.

Exemplificação: 
`  
// Transforma a palavra em minúsculas para evitar problemas de case sensitivity

palavra = palavra.toLowerCase();
`

2023-10-09 17:27 UTC, aLiviaMs commented on src/exercicio-01.ts
> +  const vogais = ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U']
Além disso, este array não comporta **acentos**.
A palavra: vovó, por exemplo, seria caracterizada com apenas uma vogal, quando, na verdade, existem duas.

Neste caso recomendo utilizar uma expressão regular (regex), desta forma é dispensado o uso do array.

`const vogais = palavra.match(/[aeiouáàâãéêíóôõúü]/g);`
desta forma a própria const vogais já armazenará o tanto de vogais `vogais.length`.

Segue documentação para entender melhor sobre o uso de regex e sua ótima utilidade na programação.

[MDN Web Docs (JavaScript)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)

2023-10-09 17:27 UTC, aLiviaMs commented on src/exercicio-01.ts
> +  const vogais = ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U']
É importante tipar todas as variáveis também.

2023-10-09 18:47 UTC, charles-oliveira commented on src/exercicio-01.ts
> +  const vogais = ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U']
Encontrei a seguinte regex usando a flag g = global e i = case insensitive, dessa maneira const vogaisRegex = /[aeiouáàâãéêíóôõúü]/gi, daí não precisei usar palavra = palavra.toLowerCase().

2023-10-09 22:16 UTC, aLiviaMs commented on src/exercicio-01.ts
> +  const vogais = ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U']
> Encontrei a seguinte regex usando a **flag g = global** e **i = case insensitive**, dessa maneira const `vogaisRegex = /[aeiouáàâãéêíóôõúü]/gi`, daí não precisei usar `palavra = palavra.toLowerCase().`

Muito bom!

2023-10-09 22:17 UTC, aLiviaMs approved these changes

2023-10-09 22:18 UTC, merged

2023-10-12 15:22 UTC, hernangior commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ squad-bellatrix ][ hernandez giordano ] Exercício 01](https://trello.com/c/FCWv3jyM/104-squad-bellatrix-hernandez-giordano-exerc%C3%ADcio-01)