Resolução do segundo exercício
charles-oliveira/orion-bootcamp pull request #2
Opened 2023-10-11 18:19 UTC by charles-oliveira

2023-10-11 19:10 UTC, Ricardonovais1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Ricardo Novais] Exercício-03](https://trello.com/c/TTOwbZbq/86-ricardo-novais-exerc%C3%ADcio-03)

2023-10-11 21:26 UTC, aLiviaMs requested changes
Os códigos estão muito bons, apenas algumas correções de tipagem e boas práticas a serem feitas.
Ótima ideia separar a lista e interface em um outro arquivo, parabens.

2023-10-11 21:26 UTC, aLiviaMs commented on src/funcional.ts
> +  const item = lista.find(obj => obj['id'] === id)
tente manter um padrão de linguagem, se estiver usando inglês, utilize tudo em inglês, misturar ambas as línguas não é uma boa prática.

2023-10-11 21:26 UTC, aLiviaMs commented on src/funcional.ts
> +const getBioByIdFuncional = (id: number) => {
Faltou a tipagem do retorno de todas as funções.

2023-10-11 21:26 UTC, aLiviaMs commented on src/funcional.ts
> +  const item = lista.find(obj => obj['id'] === id)
É importante tipar todas as variaveis dos seus códigos.

2023-10-12 03:43 UTC, charles-oliveira commented on src/funcional.ts
> +  const item = lista.find(obj => obj['id'] === id)
Vou me atentar a isso, Liv. Muito obrigado pelo conselho!!

2023-10-12 03:57 UTC, charles-oliveira commented on src/funcional.ts
> +const getBioByIdFuncional = (id: number) => {
Corrigi todas as tipagens do paradigma funcional.

2023-10-12 14:09 UTC, charles-oliveira commented on src/funcional.ts
> +  const item = lista.find(obj => obj['id'] === id)
Corrigido.

2023-10-12 14:16 UTC, charles-oliveira commented on src/funcional.ts
> +  const item = lista.find(obj => obj['id'] === id)
Tipagens corrigidas.

2023-10-13 14:47 UTC, aLiviaMs approved these changes

2023-10-13 14:47 UTC, merged